---
name: test

on: pull_request

permissions: {}
env:
  AQUA_LOG_COLOR: always

jobs:
  path-filter:
    # Get changed files to filter jobs
    timeout-minutes: 30
    outputs:
      update-aqua-checksums: ${{steps.changes.outputs.update-aqua-checksums}}
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
      ghalint: ${{steps.changes.outputs.ghalint}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            update-aqua-checksums:
              - aqua/aqua.yaml
              - aqua/imports/*.yaml
              - aqua/aqua-checksums.json
              - .github/workflows/test.yaml
            renovate-config-validator:
              - renovate.json5
              - .github/workflows/wc-renovate-config-validator.yaml
              - .github/workflows/test.yaml
            ghalint:
              - .github/workflows/*.yaml
              - aqua/imports/ghalint.yaml

  status-check:
    # This job is used for main branch's branch protection rule's status check.
    # If all dependent jobs succeed or are skipped this job succeeds.
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs:
      - renovate-config-validator
      - typos
      - ghalint
      - update-aqua-checksums
    permissions: {}
    if: failure()
    steps:
      - run: exit 1

  renovate-config-validator:
    # Validate Renovate Configuration by renovate-config-validator.
    uses: suzuki-shunsuke/renovate-config-validator-workflow/.github/workflows/validate.yaml@e8effbd185cbe3874cddef63f48b8bdcfc9ada55 # v0.2.4
    needs: path-filter
    if: needs.path-filter.outputs.renovate-config-validator == 'true'
    permissions:
      contents: read

  update-aqua-checksums:
    uses: ./.github/workflows/wc-update-aqua-checksums.yaml
    needs: path-filter
    permissions:
      contents: read
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
    if: |
      needs.path-filter.outputs.update-aqua-checksums == 'true'

  ghalint:
    # Validate GitHub Actions Workflows by ghalint.
    timeout-minutes: 30
    needs: path-filter
    if: needs.path-filter.outputs.ghalint == 'true'
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
        with:
          aqua_version: v2.44.1
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: ghalint run
        env:
          GHALINT_LOG_COLOR: always

  typos:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
        with:
          aqua_version: v2.44.1
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: typos
