---
name: test (workflow_call)
on: workflow_call
permissions: {}
env:
  AQUA_LOG_COLOR: always
jobs:
  path-filter:
    # Get changed files to filter jobs
    timeout-minutes: 10
    outputs:
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
      ghalint: ${{steps.changes.outputs.ghalint}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: changes
        with:
          filters: |
            renovate-config-validator:
              - renovate.json5
              - .github/workflows/wc-renovate-config-validator.yaml
              - .github/workflows/test.yaml
            ghalint:
              - .github/workflows/*.yaml
              - aqua/imports/ghalint.yaml

  renovate-config-validator:
    # Validate Renovate Configuration by renovate-config-validator.
    uses: suzuki-shunsuke/renovate-config-validator-workflow/.github/workflows/validate.yaml@dcf025732ed76061838048f7f8b0099ae0e89876 # v0.2.5
    needs: path-filter
    if: needs.path-filter.outputs.renovate-config-validator == 'true'
    permissions:
      contents: read

  ghalint:
    # Validate GitHub Actions Workflows by ghalint.
    timeout-minutes: 10
    needs: path-filter
    if: needs.path-filter.outputs.ghalint == 'true'
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.61.0
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: ghalint run
        env:
          GHALINT_LOG_COLOR: always

  typos:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.61.0
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: typos

